name: Scheduled dependencies update
on:
  schedule:
    - cron: '0 2 * * 1-5'
  workflow_dispatch:

jobs:
  update-deps:
    name: Update Node dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/

      # - name: Update package.json
      #   run: npx npm-check-updates@latest -u -t latest
      #   env:
      #     NCU_VERSION: ${{ inputs.npm-check-updates-version }}
      #     TARGET_VERSION: ${{ inputs.target-version }}

      - name: Install dependencies from lockfile
        run: npm ci

      - name: Update lock file
        run: npm update

      - name: Build packages
        run: npm run build --if-present

      - name: Run Tests
        run: npm run test --if-present

      - name: Git Commit/Push Changes
        uses: actions-x/commit@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          message: 'chore: Bumped dependencies in-scope [skip-ci]'
      